name: THOR [Simplex] AD 250
target_size: &target_size !!python/tuple [128, 128]
train_batch_size: &tbatch_size 16
downstream_batch_size: &dbatch_size 1
checkpoint_path: &checkpoint_path './weights/thor/thor/'
#
# Experiment
#
experiment:
  name: THOR-WXR
  task: train # test
  weights: #'.PATH_TO_WEIGHTS/latest_model.pt' # Simplex 

device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params:
#
# Model
#
model:
  module_name: model_zoo.ddpm
  class_name: DDPM
  params:
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    num_channels: 
      - 128
      - 256
      - 256
    attention_levels:
      - False
      - True
      - True
    num_res_blocks: 1
    num_head_channels: 256

    # Scheduling and noising scheme
    train_scheduler: "ddpm"
    inference_scheduler: "ddpm"
    inference_steps: 1000
    noise_level_recon: 250 # 400
    noise_type: "simplex" # Change to 'simplex' for Simplex noise
    prediction_type: "epsilon"
    inference_type: "thor"
    t_harmonization: 
      - 200
      - 150
      - 100
      - 50
#
# Trainer
#
trainer:
  module_name: projects.thor.AnoTrainer
  class_name: PTrainer
  params:
    input_size: *target_size
    checkpoint_path: *checkpoint_path
    batch_size: *tbatch_size
    nr_epochs: 1500
    val_interval: 50
    # Loss
    loss:
      module_name: optim.losses.ln_losses
      class_name: L2
      params:
    patience: 1500
    optimizer_params:
      lr: 1.0e-4
  data_loader:
# CXR
    module_name: core.DataLoader
    class_name: DefaultDataLoader
    params:
      args:
        dataset_module:
          module_name: data.loaders.xray_loader
          class_name: RayLoader
        data_dir:
          train:
            - './data/wrist/splits/train_normal.csv'
          val:
            - './data/wrist/splits/val_normal.csv'
          test:
            - './data/wrist/splits/test_metal.csv'
        target_size: *target_size
        #        batch_size: 128 # orig
        batch_size: 16
# Downstream tasks
downstream_tasks:
#  thresholding:
#    module_name: projects.thor.DownstreamEvaluatorWXR
#    class_name: PDownstreamEvaluator
#    checkpoint_path: *checkpoint_path
#    compute_fid: False
#    compute_scores: True
#    data_loader:
#      module_name: core.DataLoader
#      class_name: DefaultDataLoader
#      params:
#        args:
#          dataset_module:
#            module_name: data.loaders.xray_loader
#            class_name: RayLoader
#          target_size: *target_size
#          batch_size: *dbatch_size
#      datasets:
#        Normal_XR:
#          data_dir:
#            test:
#            - './data/wrist/splits/test_normal.csv'
  pediatric:
    module_name: projects.thor.DownstreamEvaluatorWXR
    class_name: PDownstreamEvaluator
    checkpoint_path: *checkpoint_path
    global_detection: False
    data_loader:
      module_name: core.DataLoader
      class_name: DefaultDataLoader
      params:
        args:
          dataset_module:
            module_name: data.loaders.xray_loader
            class_name: RayLoader
          target_size: *target_size
          batch_size: *dbatch_size
      datasets:
        boneanomaly:
          data_dir:
            test:
              - './data/wrist/splits/boneanomaly.csv'
          label_dir:
            test:
              - './data/wrist/splits/boneanomaly_ann.csv'
          mask_dir:
            test:
              - './data/wrist/splits/boneanomaly_neg.csv'
        foreignbody:
          data_dir:
            test:
              - './data/wrist/splits/foreignbody.csv'
          label_dir:
            test:
              - './data/wrist/splits/foreignbody_ann.csv'
          mask_dir:
            test:
              - './data/wrist/splits/foreignbody_neg.csv'
        fracture:
          data_dir:
            test:
              - './data/wrist/splits/fracture.csv'
          label_dir:
            test:
              - './data/wrist/splits/fracture_ann.csv'
          mask_dir:
            test:
              - './data/wrist/splits/fracture_neg.csv'
        metal:
          data_dir:
            test:
              - './data/wrist/splits/metal.csv'
          label_dir:
            test:
              - './data/wrist/splits/metal_ann.csv'
          mask_dir:
            test:
              - './data/wrist/splits/metal_neg.csv'
        periostealreaction:
          data_dir:
            test:
              - './data/wrist/splits/periostealreaction.csv'
          label_dir:
            test:
              - './data/wrist/splits/periostealreaction_ann.csv'
          mask_dir:
            test:
              - './data/wrist/splits/periostealreaction_neg.csv'
        softtissue:
          data_dir:
            test:
              - './data/wrist/splits/softtissue.csv'
          label_dir:
            test:
              - './data/wrist/splits/softtissue_ann.csv'
          mask_dir:
            test:
              - './data/wrist/splits/softtissue_neg.csv'
      # #  text:
      #    data_dir:
      #      test:
      #        - './data/wrist/splits/text.csv'
      #    label_dir:
      #      test:
      #        - './data/wrist/splits/text_ann.csv'
      #    mask_dir:
      #      test:
      #        - './data/wrist/splits/text_neg.csv'